config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "filter_auditoria", to: "static_pages#filter_auditoria"
  get "get_schedules", to: "static_pages#get_schedules"
  post "get_schedule_id_from_client", to: "booking_seats#get_schedule_id_from_client"
  post "get_auditorium_id_from_client", to: "static_pages#get_auditorium_id_from_client"
  resources :booking_seats
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auditorium.rb
class Auditorium < ApplicationRecord
  acts_as_paranoid

  belongs_to :cinema
  has_many :schedules
  has_many :seats
  scope :by_cinema, ->(cinema_id){where cinema_id: cinema_id}
  scope :by_cinema_and_movie, ->(cinema_id, movie_id){where cinema_id: cinema_id,
    movie_id: movie_id}
end

app/models/cinema.rb
class Cinema < ApplicationRecord
  acts_as_paranoid

  has_many :auditoria
end

app/models/movie.rb
class Movie < ApplicationRecord
  acts_as_paranoid
  serialize :genre, Array

  has_many :schedules
  has_many :auditoriums, through: :schedules
  has_many :cinemas, through: :auditoriums
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  acts_as_paranoid

  belongs_to :seat
  belongs_to :user
  belongs_to :schedule
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  acts_as_paranoid

  belongs_to :movie
  belongs_to :auditorium
  has_many :reservations

  scope :by_auditorium, ->(auditorium_id){where auditorium_id: auditorium_id}
  scope :by_auditorium_and_movie, ->(auditorium_id, movie_id){where auditorium_id: auditorium_id,
    movie_id: movie_id}
end

app/models/seat.rb
class Seat < ApplicationRecord
  acts_as_paranoid

  belongs_to :auditorium
  has_many :reservations
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable
  has_many :reservations

  validates :name, presence: true, length: {maximum: Settings.models.user.name.max_length,
    minimum: Settings.models.user.name.min_length}
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :phone_number, length: {maximum: Settings.models.user.phone_number.max_length}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end
end

app/controllers/booking_seats_controller.rb
class BookingSeatsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_movie

  def new
    @cinemas = @movie.cinemas.includes(:auditoria).uniq
    @auditoria = Auditorium.all.includes :schedules
    @movies = Movie.all.includes :schedules
    if session[:auditorium_id].nil?
      @seats = Seat.where auditorium_id: 2
    else
      @seats = Seat.where auditorium_id: session[:auditorium_id]
    end
  end

  def create
    reservations = []
    if params[:seat_id]
      params[:seat_id].each do |seat_id|
        reservation = Reservation.new seat_params.merge(seat_id: seat_id, schedule_id: session[:schedule_id])
        reservations << reservation
      end

      if Reservation.import! reservations
        ReservationMailer.reservation_complete(current_user, reservations).deliver_now
        redirect_to root_path
        flash[:success] = t ".create_success"
      else
        flash.now[:danger] = t ".create_failed"
      end
    else
      flash.now[:danger] = "Chưa chọn ghế"
    end
  end

  def get_schedule_id_from_client
    session[:schedule_id] = params[:schedule_id]
  end

  private

  def load_movie
    @movie = Movie.find_by id: params[:movie_id]
  end

  def seat_params
    params.permit :user_id
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.page(params[:page]).includes :schedules
    @cinemas = Cinema.all.includes :auditoria
    @auditoria = Auditorium.all.includes :schedules
    if session[:auditorium_id].nil?
      @seats = Seat.where auditorium_id: 2
    else
      @seats = Seat.where auditorium_id: session[:auditorium_id]
    end
  end

  def show
    @movie = Movie.find_by id: params[:id]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @movie = Movie.first
    @cinemas = Cinema.all.includes :auditoria
    @auditoria = Auditorium.all.includes :schedules
    @movies = Movie.all.includes :schedules
    if session[:auditorium_id].nil?
      @seats = Seat.where auditorium_id: 2
    else
      @seats = Seat.where auditorium_id: session[:auditorium_id]
    end
  end

  def filter_auditoria
    @auditoria = Auditorium.by_cinema params[:cinema_id]
    respond_to do |format|
      format.json {render json: {auditoria: @auditoria}}
    end
  end

  def get_schedules
    @schedules = Schedule.by_auditorium_and_movie params[:auditorium_id], params[:movie_id]
    respond_to do |format|
      format.json {render json: {schedules: @schedules}}
    end
  end

  def get_auditorium_id_from_client
    session[:auditorium_id] = params[:auditorium_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    option = "{'closeButton': true}"
    flash.each do |type, message|
      type = "success" if type == "notice"
      type = "error" if type == "alert"
      text = "toastr.#{type}('#{message}');"
      flash_messages << text if message
    end
    flash_messages.join("\n")
  end
end

app/helpers/booking_seats_helper.rb
module BookingSeatsHelper
  def booked_seat schedule_id, seat_id
    reservation = Reservation.find_by schedule_id: schedule_id, seat_id: seat_id
    reservation ? "red-highlight" : ""
  end
end

app/views/booking_seats/_form.html.erb
<div id="order">
  <div class="container">
    <div class="row order-content">
      <div class="col-sm-9 col-xs-12 seat_content ph0">
        <h2>Đặt vé</h2>
        <div class="zoom-button-container">
          <span id="zoom-in" class="btn btn-default zoom-button button display-none">+ Phóng to</span>
          <span id="zoom-out" class="btn btn-default zoom-button button display-none">- Thu nhỏ</span>
        </div>
        <div class="entry-order-content">
          <div id="msform" name="msform">
            <fieldset class="select-info-movie">
              <div class="wpc-content">
                <h3>Chọn rạp phim</h3>
                <%= select_tag :select_cinema,
                  options_from_collection_for_select(@cinemas, :id, :name) %>
                <h3 class="mt3">Chọn phòng chiếu</h3>
                <%= select_tag :select_auditorium,
                  options_from_collection_for_select(Cinema.first.auditoria, :id, :name) %>
                <h3 class="mt3">Chọn phim</h3>
                <%= select_tag :select_movie,
                  options_from_collection_for_select(@movies, :id, :title) %>
                <h3 class="mt3">Lịch chiếu</h3>
                <ul class="order-date"><span>Chưa có lịch chiếu</span></ul>
              </div>
            </fieldset>
            <fieldset class="seat-content">
              <div class="wpc-content">
                <% if @seats.size == 200 %>
                  <%= render "booking_seats/seat_map" %>
                <% elsif @seats.size == 300 %>
                  <%= render "booking_seats/seat_map_300" %>
                <% else %>
                  <%= render "booking_seats/seat_map_400" %>
                <% end %>
                <div id="legend"></div>
              </div>
            </fieldset>
          </div>
        </div>
      </div>
      <div class="col-sm-3 col-xs-12 order_sidebar ph0">
        <h2>Thông tin vé</h2>
        <div class="order-details">
          <span> Rạp phim:</span>
          <p id="locationp">CGV</p>
          <span> Phòng chiếu:</span>
          <p id="auditoriump"></p>
          <span> Phim:</span>
          <p id="moviep"></p>
          <span>Giờ chiếu:</span>
          <p id="timep"></p>
          <span>Ghế: </span>
          <ul id="selected-seats"></ul>
          <div>Số lượng vé: <span id="counter">0</span></div>
          <div>
            <button id="submit-booking">Đặt vé</button>
          </div>
        </div>
        <a href="javascript:;" class="close-window"><i class="fa fa-times"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/booking_seats/_form_movie.html.erb
<div id="order order_movie">
  <div class="container">
    <div class="row order-content">
      <div class="col-sm-9 col-xs-12 seat_content ph0">
        <h2>Đặt vé</h2>
        <div class="zoom-button-container">
          <span id="zoom-in" class="btn btn-default zoom-button button display-none">+ Phóng to</span>
          <span id="zoom-out" class="btn btn-default zoom-button button display-none">- Thu nhỏ</span>
        </div>
        <div class="entry-order-content">
          <div id="msform" name="msform">
            <fieldset class="select-info-movie">
              <div class="wpc-content">
                <h3>Chọn rạp phim</h3>
                <%= select_tag :select_cinema,
                  options_from_collection_for_select(@cinemas, :id, :name) %>
                <h3 class="mt3">Chọn phòng chiếu</h3>
                <%= select_tag :select_auditorium,
                  options_from_collection_for_select(Cinema.first.auditoria, :id, :name) %>
                <h3 class="mt3">Phim chiếu</h3>
                <%= @movie.title if params[:movie_id] %>
                <%#= select_tag :select_movie,
                  options_from_collection_for_select(@movies, :id, :title) %>
                <h3 class="mt3">Lịch chiếu</h3>
                <ul class="order-date"><span>Chưa có lịch chiếu</span></ul>
              </div>
            </fieldset>
            <fieldset class="seat-content">
              <div class="wpc-content">
                <% if @seats.size == 200 %>
                  <%= render "booking_seats/seat_map" %>
                <% elsif @seats.size == 300 %>
                  <%= render "booking_seats/seat_map_300" %>
                <% else %>
                  <%= render "booking_seats/seat_map_400" %>
                <% end %>
                <div id="legend"></div>
              </div>
            </fieldset>
          </div>
        </div>
      </div>
      <div class="col-sm-3 col-xs-12 order_sidebar ph0">
        <h2>Thông tin vé</h2>
        <div class="order-details">
          <span> Rạp phim:</span>
          <p id="locationp">CGV</p>
          <span> Phòng chiếu:</span>
          <p id="auditoriump"></p>
          <span> Phim:</span>
          <p id="moviep"><%= @movie.title if params[:movie_id]%></p>
          <span>Giờ chiếu:</span>
          <p id="timep"></p>
          <span>Ghế: </span>
          <ul id="selected-seats"></ul>
          <div>Số lượng vé: <span id="counter">0</span></div>
          <div>
            <button id="submit-booking">Đặt vé</button>
          </div>
        </div>
        <a href="javascript:;" class="close-window"><i class="fa fa-times"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/booking_seats/_seat_map.html.erb
<div class="seat-map">
  <div class="cinema-screen"></div>
  <%= form_tag booking_seats_path, id: "form-seat", method: :post do %>
    <table class="table" id="seat-map-table">
      <tbody>
        <% ("A".."E").each do |row| %>
          <tr class="row-center">
            <% 8.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td id="<%= seat.id %>" class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
            <% 8.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
          </tr>
        <% end %>
        <% ("F".."J").each do |row| %>
          <tr>
            <% 3.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
            <% 3.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
          </tr>
        <% end %>
        <% ("K".."L").each do |row| %>
          <tr>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/booking_seats/_seat_map_300.html.erb
<div class="seat-map">
  <div class="cinema-screen"></div>
  <%= form_tag booking_seats_path, id: "form-seat", method: :post do %>
    <table class="table" id="seat-map-table">
      <tbody>
        <% ("A".."E").each do |row| %>
          <tr>
            <% 5.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td id="<%= seat.id %>" class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
          </tr>
        <% end %>
        <% ("F".."M").each do |row| %>
          <tr>
            <% 5.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
          </tr>
        <% end %>
        <% ("N".."O").each do |row| %>
          <tr>
            <% 5.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
            <% 8.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
          </tr>
        <% end %>
        <% ("P".."R").each do |row| %>
          <tr>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/booking_seats/_seat_map_400.html.erb
<div class="seat-map">
  <div class="cinema-screen"></div>
  <%= form_tag booking_seats_path, id: "form-seat", method: :post do %>
    <table class="table" id="seat-map-table">
      <tbody>
        <% ("A".."E").each do |row| %>
          <tr>
            <% 8.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td id="<%= seat.id %>" class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
            <% 8.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
          </tr>
        <% end %>
        <% ("F".."K").each do |row| %>
          <tr>
            <% 7.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
            <% 7.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
          </tr>
        <% end %>
        <% ("L".."O").each do |row| %>
          <tr>
            <% 6.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
            <% 6.times.each do |n| %>
              <td class="hidden-td"></td>
            <%end %>
          </tr>
        <% end %>
        <% ("P".."T").each do |row| %>
          <tr>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
          </tr>
        <% end %>
        <% ("U".."X").each do |row| %>
          <tr>
            <% @seats.where(row:row).each do |seat| %>
              <td class="<%= booked_seat session[:schedule_id], seat.id %>">
                <%= check_box_tag "seat_id[]", seat.id %>
                <%= seat.row %><%= seat.number %>
                <%= hidden_field_tag "user_id", current_user.id %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header id="header" class="menu-top-left">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <%= link_to root_path, class: "logo-image" do %>
          Movie booking
        <% end %>
      </div>
      <div class="col-md-5 col-sm-5 col-xs-5 phl0">
        <div class="header_ticket">
          <%= link_to "Danh sách phim", movies_path %>
          <% if user_signed_in? %>
            <a href="#order" class="order_btn">Đặt vé</a>
            <%= link_to current_user.name, "#" %>
            <%= link_to t(".log_out"), destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to t(".sign_up"), new_user_registration_path %>
            <%= link_to t(".log_in"), new_user_session_path %>
          <% end %>
        </div>
      </div>
      <div class="col-md-1 col-sm-1 col-xs-1 phl0">
        <div class="button_container" id="toggle">
          <span class="top"></span>
          <span class="middle"></span>
          <span class="bottom"></span>
        </div>
      </div>
      <div class="overlay" id="overlay">
        <a href="javascript:;" class="close-window"></a>
        <nav class="overlay-menu">
          <ul >
            <li><%= link_to "Trang chủ", root_path %></li>
            <% if user_signed_in? %>
              <li><a href="#order" class="order_btn">Đặt vé</a></li>
              <li><%= link_to t(".log_out"), destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to t(".sign_up"), new_user_registration_path %></li>
              <li><%= link_to t(".log_in"), new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.6/css/swiper.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.6/css/swiper.min.css">
  </head>

  <body class="sticky-menu">
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.6/js/swiper.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.6/js/swiper.min.js"></script>
    <script src="https://unpkg.com/panzoom@7.1.2/dist/panzoom.min.js"></script>
    <script>
      <%= sanitize custom_bootstrap_flash %>
    </script>
  </body>
</html>

app/views/movies/index.html.erb
<div class="section-content">
  <div class="fullscreen-section bg-black pvb0">
    <div class="container wpc-boxoffice pv8">
      <div class="row">
        <div class="col-sm-12 col-xs-12">
          <h3>Tất cả phim</h3>
          <ul class="wpc-box-list">
            <% @movies.each_with_index do |movie, index| %>
              <li class="wpc-box-item" >
                <ol>
                  <li class="bx-item-t">
                    <%= link_to image_tag(movie.cover, class: "movie-thumb"), movie_path(movie) if movie.cover%>
                  </li>
                  <li class="bx-item-c"><%= index + 1 %></li>
                  <li class="bx-item-title">
                    <h4><%= link_to movie.title, movie_path(movie), class: "link-no-decoration" %></h4>
                    <span></span>
                    <span><%= movie.genre.join(', ')%></span>
                  </li>
                  <li class="bx-item-d"><%= movie.duration %> GIỜ</li>
                  <li class="bx-item-m">
                    <%= button_to "Đặt Vé", new_booking_seat_path, class: "book-ticket-movie",
                      method: :get, params: {movie_id: movie.id} %>
                  </li>
                </ol>
              </li>
            <% end %>
          </ul>
          <%= paginate @movies %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <%= render "booking_seats/form" %>
<% end %>

app/views/movies/show.html.erb
<div class="section-content pvb0 bg-cover movie-detail">
  <div class="container pvt80">
    <div class="row">
      <div class="col-md-12">
        <div id="slider_coming" class="flexslider">
          <ul class="slides">
            <li>
              <article class="product-item hover-dark">
                <div class="entry-title">
                  <ul class="subtitle">
                    <% @movie.genre.each do |genre| %>
                      <li><%= genre %></li>
                    <% end %>
                  </ul>
                  <a href="javascript:;" class="title"><%= @movie.title %></a>
                  <div class="entry-date"><span><%= @movie.duration %> GIỜ</span></div>
                </div>
                <div class="entry-desc">
                  <div class="row mh0">
                    <div class="col-md-4 col-sm-3 col-xs-12 comming_movie ph0">
                      <%= image_tag @movie.cover, class: "movie-cover-detail" if  @movie.cover %>
                    </div>
                    <div class="col-md-8 col-sm-7 col-xs-12 entry-text phl3">
                      <h3>Nội dung</h3>
                      <p><%= @movie.description %></p>
                      <%= button_to new_booking_seat_path, class: "btn order",
                        method: :get, params: {movie_id: @movie.id} do %>
                        Đặt Vé
                      <% end %>
                    </div>
                  </div>
                </div>
              </article>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="fullwidth-slider">
  <div id="headerslider" class="carousel slide">
    <ol class="carousel-indicators">
      <li data-target="#headerslider" data-slide-to="0" class="active"></li>
      <li data-target="#headerslider" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <% @movies.each do |movie| %>
        <div class="item active">
          <div class="fill" data-bg-image="<%= movie.cover ? movie.cover : "https://create.adobe.com/2015/8/25/film_fan_art/_jcr_content/article-marquee.img.jpg/1443212365018.jpg" %>">
            <div class="container movie-slider-container">
              <div class="row">
                <div class="col-sm-12 movie-slider-content">
                  <div class="slider-content" >
                    <ul class="subtitle"  data-animation="animated bounceInRight">
                      <% movie.genre.each do |genre| %>
                        <li><%= genre%> <li>
                      <% end %>
                    </ul>
                    <div class="title" data-animation="animated bounceInRight" >
                      <%= @movie.title %><i>(2017)</i>
                    </div>
                    <div class="slide_right" data-animation="animated bounceInRight">
                      <a href="javascript:;" class="btn-trailer">watch trailer</a> <a href="javascript:;" class="btn-ticket">buy ticket</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <!-- Controls -->
    <a class="carousel-control left" href="#headerslider" data-slide="prev">
    <i class="fa fa-angle-left"></i>
    </a>
    <a class="carousel-control right" href="#headerslider" data-slide="next">
    <i class="fa fa-angle-right"></i>
    </a>
  </div>
</div>

<section class="section-content">
  <div class="container-fluid pv11 ">
    <div class="row">
      <div class="col-sm-12">
        <h3 class="heading text-center">Phim đang chiếu</h3>
        <div class="ticket-carousel pvt85">
          <div class="swiper-container carousel-container movie-images" data-col="5">
            <div class="swiper-wrapper">
              <% @movies.each do |movie| %>
                <div class="swiper-slide">
                  <div class="movie-image" data-bg-image="<%= movie.cover ? movie.cover : "images/carousel/movie-1.jpg" %>">
                    <div class="entry-hover">
                      <div class="entry-actions">
                        <a href="#" class="btn-trailers video-player">watch trailer</a>
                        <%= button_to "Đặt Vé", new_booking_seat_path, class: "btn-ticket",
                          method: :get, params: {movie_id: movie.id}%>
                      </div>
                    </div>
                    <div class="entry-desc">
                      <h3 class="entry-title"><%= movie.title %></h3>
                      <ul class="entry-date">
                        <% movie.schedules.each do |schedule| %>
                          <li><%= schedule.start_time.strftime("%Y/%m/%d %H:%M:%S") %></li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
        </div>
      </div>
    </div>
  </div>
</section>

<% if user_signed_in? %>
  <%= render "booking_seats/form" %>
<% end %>